Implement MultiSwipeActionView for multiple actions
Tunous/SwipeActionView pull request #33
Opened 2023-10-04 09:56 UTC by newhinton

![Screenshot_20231004_115140](https://github.com/Tunous/SwipeActionView/assets/25279821/34bf346a-d4a3-454f-80ae-6c7f7fce10bc)

This updates this library to a newer gradle version, aswell as java and kotlin.
This implements a specific container, that allows for two children to be treated as two distinct actions. 
Technically it allows for arbitrary amounts of elements, but only the first child (for the left actions) and the last child (for the right actions)  are used as a divider.

What works:
- Callback for halfway-action (left&right)

What doesn't work:
- "Sticky" halfway-point. (The main view always returns to the initial state)
- Maven publishing. The gradle-syntax changed, and i dont know how to test this

2023-10-07 11:41 UTC, Tunous requested changes
Thank you for the pull requests. I've reviewed your code and left few code changes requests.

2023-10-07 11:41 UTC, Tunous commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
> +    private fun hasSwipedFarEnoughMultiContainerFirstElement(swipeDistance: Float): Boolean {
We can get rid of the maxSwipe checks from this function and only check the halfway condition. Then the code which uses this function could be adjusted to correctly work with new implementation (see other comments).

That way we'll be sure that there is no gap between halfway and full swipe which won't react to any actions.

2023-10-07 11:41 UTC, Tunous commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
>          } else {
These checks could be combined to only trigger halfway swipe if we are sure that regular swipe didn't activate.

```suggestion
        if (hasSwipedFarEnough(container.translationX) || swipedFastEnough) {
            activate(container.translationX > 0)
        } else if (hasSwipedFarEnoughMultiContainerFirstElement(container.translationX)) {
            activate(container.translationX > 0, true)
        } else {
```

2023-10-07 11:41 UTC, Tunous commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
> +        if(isHalfwaySwipe) {
This should be done inside animateContainer on line 858 instead of regular onSwipedRight/onSwipedLeft callback.

2023-10-07 11:41 UTC, Tunous commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
> +        var targetTranslationX = if (swipedRight) maxRightSwipeDistance else -maxLeftSwipeDistance
Add and use a function here which will calculate target position based on whether its halfway swipe by accessing first child width and using that.

2023-10-07 11:41 UTC, Tunous commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
> +                    swipeGestureListener?.onSwipeLeftComplete(this)
Unnecessary change
```suggestion
```

2023-10-12 08:54 UTC, newhinton commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
> +        if(isHalfwaySwipe) {
Do you mean the `finishDrag()` function?

2023-10-12 09:48 UTC, Tunous commented on library/src/main/kotlin/me/thanel/swipeactionview/SwipeActionView.kt
> +        if(isHalfwaySwipe) {
Calls to `onSwipedHalfwayRight/onSwipedHalfwayLeft` should replace calls to `onSwipedRight/onSwipedLeft` if it is a halfway swipe. In this function (line 858/935 to 862/939). Right now both of them will be called

2023-10-29 15:08 UTC, Tunous approved these changes
Thank you, looks good now. I've only pushed a small fix where swipe position was incorrect.
Will try to figure out the new publishing workflow and hopefully release a new version with your changes.

2023-10-29 15:09 UTC, Tunous commented
Closes #19

2023-10-29 15:09 UTC, merged